### ISSUE TITLE
bug: kubearmor make run in local fail

### ISSUE THREAD

**Issue by xiao-jay** [kubearmor/KubeArmor#1176]
## Bug Report

I want to build and run KubeArmor in local , Ubuntu 20.0,go version 1.20.2
exec `make run`
```
root@yyj-test-master1:/home/ubuntu/kubearmor/KubeArmor/KubeArmor# make run
sudo make -C ../protobuf
make: Entering directory '/home/ubuntu/kubearmor/KubeArmor/protobuf'
make: Nothing to be done for 'build'.
make: Leaving directory '/home/ubuntu/kubearmor/KubeArmor/protobuf'
sudo go mod tidy
sudo go build  -o kubearmor main.go
kubectl apply -f ../deployments/CRD/KubeArmorPolicy.yaml
customresourcedefinition.apiextensions.k8s.io/kubearmorpolicies.security.kubearmor.com configured
kubectl apply -f ../deployments/CRD/KubeArmorHostPolicy.yaml
customresourcedefinition.apiextensions.k8s.io/kubearmorhostpolicies.security.kubearmor.com configured
sudo rm -f /tmp/kubearmor.log
cd /home/ubuntu/kubearmor/KubeArmor/KubeArmor/BPF; make clean
make[1]: Entering directory '/home/ubuntu/kubearmor/KubeArmor/KubeArmor/BPF'
make[2]: Entering directory '/home/ubuntu/kubearmor/KubeArmor/KubeArmor/BPF/tests'
rm: cannot remove 'syscheck': No such file or directory
make[2]: Leaving directory '/home/ubuntu/kubearmor/KubeArmor/KubeArmor/BPF/tests'
make[1]: Leaving directory '/home/ubuntu/kubearmor/KubeArmor/KubeArmor/BPF'
cd /home/ubuntu/kubearmor/KubeArmor/KubeArmor/BPF; make
make[1]: Entering directory '/home/ubuntu/kubearmor/KubeArmor/KubeArmor/BPF'
Kernel BTF information found
Generating vmlinux.h for kernel 5.15.0
make[2]: Entering directory '/home/ubuntu/kubearmor/KubeArmor/KubeArmor/BPF/tests'
Compiling eBPF bytecode: checks/security_path_unlink.c ...
Compiling syscheck ...
# internal/goarch
compile: version "go1.20.1" does not match go tool version "go1.20.2"
# internal/unsafeheader
compile: version "go1.20.1" does not match go tool version "go1.20.2"
# internal/coverage/rtcov
compile: version "go1.20.1" does not match go tool version "go1.20.2"
# internal/cpu
compile: version "go1.20.1" does not match go tool version "go1.20.2"
# internal/goexperiment
compile: version "go1.20.1" does not match go tool version "go1.20.2"
# internal/goos
compile: version "go1.20.1" does not match go tool version "go1.20.2"
# runtime/internal/syscall
compile: version "go1.20.1" does not match go tool version "go1.20.2"
# runtime/internal/atomic
compile: version "go1.20.1" does not match go tool version "go1.20.2"
# internal/itoa
compile: version "go1.20.1" does not match go tool version "go1.20.2"
# math/bits
compile: version "go1.20.1" does not match go tool version "go1.20.2"
# unicode/utf8
compile: version "go1.20.1" does not match go tool version "go1.20.2"
# internal/race
compile: version "go1.20.1" does not match go tool version "go1.20.2"
# sync/atomic
compile: version "go1.20.1" does not match go tool version "go1.20.2"
# encoding
compile: version "go1.20.1" does not match go tool version "go1.20.2"
# unicode
compile: version "go1.20.1" does not match go tool version "go1.20.2"
# crypto/internal/alias
compile: version "go1.20.1" does not match go tool version "go1.20.2"
# crypto/subtle
compile: version "go1.20.1" does not match go tool version "go1.20.2"
# crypto/internal/boring/sig
compile: version "go1.20.1" does not match go tool version "go1.20.2"
# golang.org/x/sys/internal/unsafeheader
compile: version "go1.20.1" does not match go tool version "go1.20.2"
Golang was not found in your system please install it to proceed
Checking syscall checks/security_path_unlink
sudo: ./syscheck: command not found
Disabling security_path_unlink ...
make[2]: Leaving directory '/home/ubuntu/kubearmor/KubeArmor/KubeArmor/BPF/tests'
Compiling eBPF bytecode: system_monitor.bpf.o ...
Using Compiler flags: 
Compiling eBPF bytecode: system_monitor.container.bpf.o ...
Using Compiler flags: 
Compiling eBPF bytecode: system_monitor.host.bpf.o ...
Using Compiler flags: 
make[1]: Leaving directory '/home/ubuntu/kubearmor/KubeArmor/KubeArmor/BPF'
sudo -E ./kubearmor -logPath=/tmp/kubearmor.log -enableKubeArmorPolicy -enableKubeArmorHostPolicy -hostVisibility=process,file,network,capabilities -defaultFilePosture block -defaultCapabilitiesPosture block -defaultNetworkPosture block -hostDefaultFilePosture block -hostDefaultCapabilitiesPosture block -hostDefaultNetworkPosture block
2023-03-19 11:53:39.327416      INFO    Arguments [bpfFsPath:/sys/fs/bpf cluster:default coverageTest:false criSocket: defaultCapabilitiesPosture:audit defaultFilePosture:audit defaultNetworkPosture:audit enableKubeArmorHostPolicy:false enableKubeArmorPolicy:true enableKubeArmorVm:false gRPC:32767 host:yyj-test-master1 hostDefaultCapabilitiesPosture:audit hostDefaultFilePosture:audit hostDefaultNetworkPosture:audit hostVisibility:default k8s:true kubeconfig: logPath:none lsm:bpf,apparmor,selinux seLinuxProfileDir:/tmp/kubearmor.selinux visibility:process,file,network,capabilities]
2023-03-19 11:53:39.327817      INFO    Configuration [{Cluster:default Host:yyj-test-master1 GRPC:32767 LogPath:/tmp/kubearmor.log SELinuxProfileDir:/tmp/kubearmor.selinux CRISocket: Visibility:process,file,network,capabilities HostVisibility:process,file,network,capabilities Policy:true HostPolicy:true KVMAgent:false K8sEnv:true DefaultFilePosture:block DefaultNetworkPosture:block DefaultCapabilitiesPosture:block HostDefaultFilePosture:block HostDefaultNetworkPosture:block HostDefaultCapabilitiesPosture:block CoverageTest:false LsmOrder:[] BPFFsPath:}]
2023-03-19 11:53:39.327978      INFO    Final Configuration [{Cluster:default Host:yyj-test-master1 GRPC:32767 LogPath:/tmp/kubearmor.log SELinuxProfileDir:/tmp/kubearmor.selinux CRISocket: Visibility:process,file,network,capabilities HostVisibility:process,file,network,capabilities Policy:true HostPolicy:true KVMAgent:false K8sEnv:true DefaultFilePosture:block DefaultNetworkPosture:block DefaultCapabilitiesPosture:block HostDefaultFilePosture:block HostDefaultNetworkPosture:block HostDefaultCapabilitiesPosture:block CoverageTest:false LsmOrder:[bpf apparmor selinux] BPFFsPath:/sys/fs/bpf}]
2023-03-19 11:53:39.329445      INFO    Initialized Kubernetes client
2023-03-19 11:53:39.329507      INFO    Started to monitor node events
2023-03-19 11:53:39.329644      INFO    GlobalCfg.Host=yyj-test-master1, KUBEARMOR_NODENAME=
2023-03-19 11:53:40.330006      INFO    Node Name: yyj-test-master1
2023-03-19 11:53:40.330177      INFO    Node IP: 10.35.128.114
2023-03-19 11:53:40.330250      INFO    Node Annotations: map[kubeadm.alpha.kubernetes.io/cri-socket:unix:///run/containerd/containerd.sock kubearmor-policy:enabled kubearmor-visibility:process,file,network,capabilities node.alpha.kubernetes.io/ttl:0 projectcalico.org/IPv4Address:192.168.0.123/24 projectcalico.org/IPv4IPIPTunnelAddr:100.115.181.64 volumes.kubernetes.io/controller-managed-attach-detach:true]
2023-03-19 11:53:40.330278      INFO    OS Image: Ubuntu 22.04.1 LTS
2023-03-19 11:53:40.330296      INFO    Kernel Version: 5.15.0-67-generic
2023-03-19 11:53:40.330333      INFO    Kubelet Version: v1.24.0
2023-03-19 11:53:40.330350      INFO    Container Runtime: containerd://1.6.16
2023-03-19 11:53:40.331155      INFO    Initialized KubeArmor Logger
2023-03-19 11:53:40.334009      INFO    Detected mounted BPF filesystem at /sys/fs/bpf
2023-03-19 11:53:40.334785      INFO    Initializing eBPF system monitor
2023-03-19 11:53:40.352906      INFO    Successfully added visibiliy map with key={PidNS:0 MntNS:0} to the kernel
2023-03-19 11:53:40.352956      INFO    eBPF system monitor object file path: /home/ubuntu/kubearmor/KubeArmor/KubeArmor/BPF/system_monitor.bpf.o
2023-03-19 11:53:52.862835      INFO    Initialized the eBPF system monitor
2023-03-19 11:53:54.536037      ERROR   Failed to initialize BPF (error loading kprobe security_path_mknod: prog cannot be nil: invalid input)
github.com/kubearmor/KubeArmor/KubeArmor/log.Errf
        /home/ubuntu/kubearmor/KubeArmor/KubeArmor/log/logger.go:103
github.com/kubearmor/KubeArmor/KubeArmor/core.(*KubeArmorDaemon).InitSystemMonitor
        /home/ubuntu/kubearmor/KubeArmor/KubeArmor/core/kubeArmor.go:232
github.com/kubearmor/KubeArmor/KubeArmor/core.KubeArmor
        /home/ubuntu/kubearmor/KubeArmor/KubeArmor/core/kubeArmor.go:435
main.main
        /home/ubuntu/kubearmor/KubeArmor/KubeArmor/main.go:54
runtime.main
        /snap/go/10073/src/runtime/proc.go:250
2023-03-19 11:53:54.536204      ERROR   Failed to initialize KubeArmor Monitor
github.com/kubearmor/KubeArmor/KubeArmor/log.Err
        /home/ubuntu/kubearmor/KubeArmor/KubeArmor/log/logger.go:98
github.com/kubearmor/KubeArmor/KubeArmor/feeder.(*Feeder).Err
        /home/ubuntu/kubearmor/KubeArmor/KubeArmor/feeder/feeder.go:486
github.com/kubearmor/KubeArmor/KubeArmor/core.KubeArmor
        /home/ubuntu/kubearmor/KubeArmor/KubeArmor/core/kubeArmor.go:436
main.main
        /home/ubuntu/kubearmor/KubeArmor/KubeArmor/main.go:54
runtime.main
        /snap/go/10073/src/runtime/proc.go:250
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x194899b]

goroutine 1 [running]:
github.com/kubearmor/KubeArmor/KubeArmor/monitor.(*SystemMonitor).DestroySystemMonitor(0xc000550780)
        /home/ubuntu/kubearmor/KubeArmor/KubeArmor/monitor/systemMonitor.go:564 +0x17b
github.com/kubearmor/KubeArmor/KubeArmor/core.(*KubeArmorDaemon).CloseSystemMonitor(0xc0000cee00)
        /home/ubuntu/kubearmor/KubeArmor/KubeArmor/core/kubeArmor.go:253 +0x2c
github.com/kubearmor/KubeArmor/KubeArmor/core.(*KubeArmorDaemon).DestroyKubeArmorDaemon(0xc0000cee00)
        /home/ubuntu/kubearmor/KubeArmor/KubeArmor/core/kubeArmor.go:150 +0x7c
github.com/kubearmor/KubeArmor/KubeArmor/core.KubeArmor()
        /home/ubuntu/kubearmor/KubeArmor/KubeArmor/core/kubeArmor.go:439 +0xbe5
main.main()
        /home/ubuntu/kubearmor/KubeArmor/KubeArmor/main.go:54 +0x1a8
make: *** [Makefile:53: run] Error 2
root@yyj-test-master1:/home/ubuntu/kubearmor/KubeArmor/KubeArmor# go version
go version go1.20.2 linux/amd64
```

**Comment by Ankurk99** [comment]
Seems like an issue with the Go environment. Can you please checkout https://stackoverflow.com/questions/46693653/compile-version-go1-9-does-not-match-go-tool-version-go1-9-1?

**Comment by nyrahul** [comment]
@DelusionalOptimist , can you check KubeArmor dev env's compat with golang > 1.20? Thanks

**Comment by DelusionalOptimist** [comment]
Folks, I'm able to build with both go 1.20.1 and 1.20.2 in the vagrant env.

@xiao-jay as pointed out by Ankur, I think it might be an issue with your go env. In your initial logs I see some of the commands from Makefile being run with sudo. Maybe that might be causing the difference in you go versions. Please check.

**Comment by xiao-jay** [comment]
> Folks, I'm able to build with both go 1.20.1 and 1.20.2 in the vagrant env.
> 
> @xiao-jay as pointed out by Ankur, I think it might be an issue with your go env. In your initial logs I see some of the commands from Makefile being run with sudo. Maybe that might be causing the difference in you go versions. Please check.

@DelusionalOptimist 
If i don't use sudo ,will appear `make[1]: go: Permission denied `.

go env
<details>

```
ubuntu@yyj-test-master1:~$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ubuntu/.cache/go-build"
GOENV="/home/ubuntu/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/ubuntu/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ubuntu/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/snap/go/10073"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/snap/go/10073/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build754771488=/tmp/go-build -gno-record-gcc-switches"
```

</details>

**Comment by xiao-jay** [comment]
I re-install go to 1.20.1 and not `sudo run go` slove the problem.
thanks @DelusionalOptimist @nyrahul

**Comment by DelusionalOptimist** [comment]
Feel free to ask any other problems you face while setting up @xiao-jay : )
