### ISSUE TITLE
[EKS] panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by yasin-cs-ko-ak** [kubearmor/KubeArmor#776]
## Bug Report

**General Information**

- Environment description - EKS
- Kernel version `Linux arch 5.18.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 15 Jul 2022 15:33:02 +0000 x86_64 GNU/Linux`

- Orchestration system version in use 
```
➜  ~ kubectl version                                                                                 
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"archive", BuildDate:"2022-06-18T07:33:51Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.10-eks-84b4fe6", GitCommit:"cc6a1b4915a99f49f5510ef0667f94b9ca832a8a", GitTreeState:"clean", BuildDate:"2022-06-09T18:24:04Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.24) and server (1.22) exceeds the supported minor version skew of +/-1
```
- Link to relevant artifacts (policies, deployments scripts, ...)
- Target containers/pods

**To Reproduce**

1. Instruction 
-> `aws eks --region <region-code> update-kubeconfig --name <cluster-name>`
-> `karmor install`
output
```
➜  ~ karmor install                                                   
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/kubearmor/kubearmor-client/install.autoDetectEnvironment(0xc000127400)
        /home/runner/work/kubearmor-client/kubearmor-client/install/install.go:363 +0x5d7
github.com/kubearmor/kubearmor-client/install.K8sInstaller(0xc000127400, {{0x1dc20e8, 0xb}, {0x1ddb80f, 0x1a}, {0x0, 0x0}, 0x0})
        /home/runner/work/kubearmor-client/kubearmor-client/install/install.go:32 +0x6e
github.com/kubearmor/kubearmor-client/cmd.glob..func4(0x2fc69c0?, {0x1db7cf8?, 0x0?, 0x0?})
        /home/runner/work/kubearmor-client/kubearmor-client/cmd/install.go:19 +0x52
github.com/spf13/cobra.(*Command).execute(0x2fc69c0, {0x301b2f8, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x2fc6c40)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/kubearmor/kubearmor-client/cmd.Execute()
        /home/runner/work/kubearmor-client/kubearmor-client/cmd/root.go:43 +0x25
main.main()
        /home/runner/work/kubearmor-client/kubearmor-client/main.go:9 +0x17
```
3. Instruction 2

**Expected behavior**

A description of what you expected to happen.

**Screenshots**

**Comment by daemon1024** [comment]
I am suspecting here the nodes are not ready!

Can you please share the output for 
`kubectl get nodes -owide`
and
Archive generate by
`karmor sysdump`?

Thank You!

**Comment by nyrahul** [comment]
Can you raise this issue on [kubearmor-client](https://github.com/kubearmor/kubearmor-client)? Thanks.

**Comment by daemon1024** [comment]
Should be handled in https://github.com/kubearmor/kubearmor-client/releases/tag/v0.7.12.

Please reopen if any updates or if you have more context for this error.
